# QQ邮箱配置
spring:
  mail:
    host: ${mail.host} #发送邮件服务器
    username: ${mail.username} #发送邮件的邮箱地址
    password: ${mail.password} #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    from: ${mail.from} # 发送邮件的地址，和上面username一致
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
