server:
  port: 9006

# 注册到Eureka服务中心
eureka:
  client:
    service-url:
      # 注册到集群，就把多个Eurekaserver地址使用逗号连接起来即可；注册到单实例（非集群模式），那就写一个就ok
      defaultZone: http://RiemannCloudEurekaServerA:9000/eureka,http://RiemannCloudEurekaServerB:9001/eureka
  instance:
    prefer-ip-address: true  # 服务实例中显示ip，而不是显示主机名（兼容老的eureka版本）
    # 实例名称
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@

spring:
  application:
    name: riemann-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/riemannChow/SpringCloudConfig #配置git服务地址
          username: # 754798352@qq.com # 配置git用户名
          password: # zhou358117139 # 配置git密码
          search-paths: repo
      # 读取分支
      label: master
  rabbitmq:
    host: 192.168.31.199
    port: 5672
    username: guest
    password: guest

# springboot中暴露健康检查等断点接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 暴露健康接口的细节
  endpoint:
    health:
      show-details: always


