server:
  port: 8763

spring:
  application:
    name: microservice-provider-service-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

# 使用属性自定义 Ribbon 配置
microservice-provider-service-hi:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


